# Flutter build
variables:
  projectDirectory: 'spark'
trigger:
- develop
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '$(projectDirectory)'
        entryPoint: 'lib/main_dev.dart'
        
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1