name: spark
description: E-Commerce project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization dependency
  intl: ^0.17.0
  # State management
  flutter_bloc: ^7.0.0
  # Service Locator
  get_it: ^6.1.1
  # prints beautiful logs
  logger: ^1.0.0
  # Functional programming in Dart
  dartz: ^0.10.0-nullsafety.1
  # shared preferences
  shared_preferences: ^2.0.5
  #  Http client for Dart
  dio: ^4.0.0
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format
  pretty_dio_logger: ^1.2.0-beta-1
  # compare objects
  equatable: ^2.0.0
  # adapting screen and font size
  flutter_screenutil: ^5.0.0
  # scroll component drop-down refresh
  pull_to_refresh: ^1.6.5
  # launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^6.0.3
  #  A simple widget wrapper to enable modal progress HUD
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # This Flutter plugin provides an API for querying information about an application package.
  package_info: ^2.0.0
  # A pure dart toast Library.
  oktoast: ^3.0.0
  # A Flutter plugin for finding commonly used locations on the filesystem.
  # Supports iOS, Android, Linux and MacOS. Not all methods are supported on all platforms.
  path_provider: ^2.0.1
  # A set of high-level APIs over PointyCastle for two-way cryptography.
  encrypt: ^5.0.0
  # Flutter Modal Bottom Sheet
  modal_bottom_sheet: ^2.0.0


  cupertino_icons: ^1.0.2


dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/png/


flutter_intl:
  main_locale: en_US
  enabled: true