name: spark
description: template project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization dependency
  intl: ^0.17.0
  # State management
  flutter_bloc: ^8.0.1
  # Service Locator
  get_it: ^7.2.0
  # prints beautiful logs
  logger: ^1.1.0
  # Functional programming in Dart
  dartz: ^0.10.1
  # shared preferences
  shared_preferences: ^2.0.12
  #  Http client for Dart
  dio: ^4.0.4
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format
  pretty_dio_logger: ^1.2.0-beta-1
  # adapting screen and font size
  flutter_screenutil: 5.1.0
  # scroll component drop-down refresh
  pull_to_refresh:
    git:
      url: git://github.com/y-alkhateeb/flutter_pulltorefresh.git
  # launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^6.0.18
  #  A simple widget wrapper to enable modal progress HUD
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # This Flutter plugin provides an API for querying information about an application package.
  package_info: ^2.0.2
  # A pure dart toast Library.
  oktoast: ^3.1.5
  # A Flutter plugin for finding commonly used locations on the filesystem.
  # Supports iOS, Android, Linux and MacOS. Not all methods are supported on all platforms.
  path_provider: ^2.0.8
  # A set of high-level APIs over PointyCastle for two-way cryptography.
  encrypt: ^5.0.1
  # Flutter Modal Bottom Sheet
  modal_bottom_sheet: ^2.0.0
  # a Flutter navigation package, it allows for strongly-typed arguments passing,
  # effortless deep-linking and it uses code generation to simplify routes setup
  auto_route: ^3.2.1
  cupertino_icons: ^1.0.4
  freezed_annotation: ^1.1.0



dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  freezed: ^1.1.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/png/


flutter_intl:
  main_locale: en_US
  enabled: true